# Generated by Django 2.2 on 2021-03-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Coding Dojo has campuses in 10 cities around the US plus an online campus.'),
            preserve_default=False,
        ),
    ]
